#
# Copyright (c) 2023-present Hutech University. All rights reserved
# Licensed under the MIT License
#
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63hat_service.proto\"\x07\n\x05\x45mpty\"\x1f\n\x0c\x44\x61taResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0b\x43hatRequest\x12\r\n\x05query\x18\x01 \x01(\t\"!\n\x0c\x43hatResponse\x12\x11\n\tdocuments\x18\x01 \x03(\t2c\n\x0b\x43hatService\x12$\n\tVectorize\x12\x06.Empty\x1a\r.DataResponse\"\x00\x12.\n\rChatRetrieval\x12\x0c.ChatRequest\x1a\r.ChatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_DATARESPONSE']._serialized_start=31
  _globals['_DATARESPONSE']._serialized_end=62
  _globals['_CHATREQUEST']._serialized_start=64
  _globals['_CHATREQUEST']._serialized_end=92
  _globals['_CHATRESPONSE']._serialized_start=94
  _globals['_CHATRESPONSE']._serialized_end=127
  _globals['_CHATSERVICE']._serialized_start=129
  _globals['_CHATSERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
