#
# Copyright (c) 2023-present Hutech University. All rights reserved
# Licensed under the MIT License
#
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15message_service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n\x15GetChatHistoryRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"<\n\x16GetChatHistoryResponse\x12\"\n\x0c\x63hat_history\x18\x01 \x03(\x0b\x32\x0c.ChatHistory\"M\n\x15\x41\x64\x64\x43hatHistoryRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"<\n\x16\x41\x64\x64\x43hatHistoryResponse\x12\"\n\x0c\x63hat_history\x18\x01 \x01(\x0b\x32\x0c.ChatHistory\"&\n\x18\x44\x65leteChatHistoryRequest\x12\n\n\x02id\x18\x01 \x01(\t\",\n\x19\x44\x65leteChatHistoryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x7f\n\x0b\x43hatHistory\x12\n\n\x02id\x18\x01 \x01(\t\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08question\x18\x03 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x04 \x01(\t\x12\x12\n\nsession_id\x18\x05 \x01(\t2\xec\x01\n\x12\x43hatHistoryService\x12\x43\n\x0eGetChatHistory\x12\x16.GetChatHistoryRequest\x1a\x17.GetChatHistoryResponse\"\x00\x12\x43\n\x0e\x41\x64\x64\x43hatHistory\x12\x16.AddChatHistoryRequest\x1a\x17.AddChatHistoryResponse\"\x00\x12L\n\x11\x44\x65leteChatHistory\x12\x19.DeleteChatHistoryRequest\x1a\x1a.DeleteChatHistoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETCHATHISTORYREQUEST']._serialized_start=58
  _globals['_GETCHATHISTORYREQUEST']._serialized_end=101
  _globals['_GETCHATHISTORYRESPONSE']._serialized_start=103
  _globals['_GETCHATHISTORYRESPONSE']._serialized_end=163
  _globals['_ADDCHATHISTORYREQUEST']._serialized_start=165
  _globals['_ADDCHATHISTORYREQUEST']._serialized_end=242
  _globals['_ADDCHATHISTORYRESPONSE']._serialized_start=244
  _globals['_ADDCHATHISTORYRESPONSE']._serialized_end=304
  _globals['_DELETECHATHISTORYREQUEST']._serialized_start=306
  _globals['_DELETECHATHISTORYREQUEST']._serialized_end=344
  _globals['_DELETECHATHISTORYRESPONSE']._serialized_start=346
  _globals['_DELETECHATHISTORYRESPONSE']._serialized_end=390
  _globals['_CHATHISTORY']._serialized_start=392
  _globals['_CHATHISTORY']._serialized_end=519
  _globals['_CHATHISTORYSERVICE']._serialized_start=522
  _globals['_CHATHISTORYSERVICE']._serialized_end=758
# @@protoc_insertion_point(module_scope)
