#
# Copyright (c) 2023-present Hutech University. All rights reserved
# Licensed under the MIT License
#
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15session_service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n\x18\x43reateChatSessionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"?\n\x19\x43reateChatSessionResponse\x12\"\n\x0c\x63hat_session\x18\x01 \x01(\x0b\x32\x0c.ChatSession\"(\n\x15GetChatSessionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"<\n\x16GetChatSessionResponse\x12\"\n\x0c\x63hat_session\x18\x01 \x01(\x0b\x32\x0c.ChatSession\"4\n\x18UpdateChatSessionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"?\n\x19UpdateChatSessionResponse\x12\"\n\x0c\x63hat_session\x18\x01 \x01(\x0b\x32\x0c.ChatSession\"&\n\x18\x44\x65leteChatSessionRequest\x12\n\n\x02id\x18\x01 \x01(\t\",\n\x19\x44\x65leteChatSessionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"h\n\x0b\x43hatSession\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07user_id\x18\x04 \x01(\t2\xc3\x02\n\x12\x43hatSessionService\x12L\n\x11\x43reateChatSession\x12\x19.CreateChatSessionRequest\x1a\x1a.CreateChatSessionResponse\"\x00\x12\x43\n\x0eGetChatSession\x12\x16.GetChatSessionRequest\x1a\x17.GetChatSessionResponse\"\x00\x12L\n\x11UpdateChatSession\x12\x19.UpdateChatSessionRequest\x1a\x1a.UpdateChatSessionResponse\"\x00\x12L\n\x11\x44\x65leteChatSession\x12\x19.DeleteChatSessionRequest\x1a\x1a.DeleteChatSessionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATECHATSESSIONREQUEST']._serialized_start=58
  _globals['_CREATECHATSESSIONREQUEST']._serialized_end=115
  _globals['_CREATECHATSESSIONRESPONSE']._serialized_start=117
  _globals['_CREATECHATSESSIONRESPONSE']._serialized_end=180
  _globals['_GETCHATSESSIONREQUEST']._serialized_start=182
  _globals['_GETCHATSESSIONREQUEST']._serialized_end=222
  _globals['_GETCHATSESSIONRESPONSE']._serialized_start=224
  _globals['_GETCHATSESSIONRESPONSE']._serialized_end=284
  _globals['_UPDATECHATSESSIONREQUEST']._serialized_start=286
  _globals['_UPDATECHATSESSIONREQUEST']._serialized_end=338
  _globals['_UPDATECHATSESSIONRESPONSE']._serialized_start=340
  _globals['_UPDATECHATSESSIONRESPONSE']._serialized_end=403
  _globals['_DELETECHATSESSIONREQUEST']._serialized_start=405
  _globals['_DELETECHATSESSIONREQUEST']._serialized_end=443
  _globals['_DELETECHATSESSIONRESPONSE']._serialized_start=445
  _globals['_DELETECHATSESSIONRESPONSE']._serialized_end=489
  _globals['_CHATSESSION']._serialized_start=491
  _globals['_CHATSESSION']._serialized_end=595
  _globals['_CHATSESSIONSERVICE']._serialized_start=598
  _globals['_CHATSESSIONSERVICE']._serialized_end=921
# @@protoc_insertion_point(module_scope)
