# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import indexing_service_pb2 as indexing__service__pb2


class IndexingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunIndexing = channel.unary_unary(
                '/IndexingService/RunIndexing',
                request_serializer=indexing__service__pb2.IndexingRequest.SerializeToString,
                response_deserializer=indexing__service__pb2.IndexingResponse.FromString,
                )


class IndexingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunIndexing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunIndexing': grpc.unary_unary_rpc_method_handler(
                    servicer.RunIndexing,
                    request_deserializer=indexing__service__pb2.IndexingRequest.FromString,
                    response_serializer=indexing__service__pb2.IndexingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IndexingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IndexingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunIndexing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IndexingService/RunIndexing',
            indexing__service__pb2.IndexingRequest.SerializeToString,
            indexing__service__pb2.IndexingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
