# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indexing_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
  b'\n\x16indexing_service.proto\"%\n\x0fIndexingRequest\x12\x12\n\nfile_paths\x18\x01 \x03('
  b'\t\"#\n\x10IndexingResponse\x12\x0f\n\x07message\x18\x01 \x01('
  b'\t2G\n\x0fIndexingService\x12\x34\n\x0bRunIndexing\x12\x10.IndexingRequest\x1a\x11.IndexingResponse\"\x00\x62'
  b'\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indexing_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._options = None
    _globals['_INDEXINGREQUEST']._serialized_start = 26
    _globals['_INDEXINGREQUEST']._serialized_end = 63
    _globals['_INDEXINGRESPONSE']._serialized_start = 65
    _globals['_INDEXINGRESPONSE']._serialized_end = 100
    _globals['_INDEXINGSERVICE']._serialized_start = 102
    _globals['_INDEXINGSERVICE']._serialized_end = 173
# @@protoc_insertion_point(module_scope)
