import './global.css';
import { ReactNode } from 'react';
import { Providers } from './providers';

export const metadata = {
  title: 'Welcome to webfront',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
