# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from search_svc.grpc import search_service_pb2 as search__service__pb2


class SearchingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Vectorize = channel.unary_unary(
                '/SearchingService/Vectorize',
                request_serializer=search__service__pb2.Empty.SerializeToString,
                response_deserializer=search__service__pb2.DataResponse.FromString,
                )
        self.VectorSearch = channel.unary_unary(
                '/SearchingService/VectorSearch',
                request_serializer=search__service__pb2.SearchRequest.SerializeToString,
                response_deserializer=search__service__pb2.SearchResponse.FromString,
                )


class SearchingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Vectorize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Vectorize': grpc.unary_unary_rpc_method_handler(
                    servicer.Vectorize,
                    request_deserializer=search__service__pb2.Empty.FromString,
                    response_serializer=search__service__pb2.DataResponse.SerializeToString,
            ),
            'VectorSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorSearch,
                    request_deserializer=search__service__pb2.SearchRequest.FromString,
                    response_serializer=search__service__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SearchingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Vectorize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SearchingService/Vectorize',
            search__service__pb2.Empty.SerializeToString,
            search__service__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VectorSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SearchingService/VectorSearch',
            search__service__pb2.SearchRequest.SerializeToString,
            search__service__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
