# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: searching_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17searching_service.proto\"%\n\x0fIndexingRequest\x12\x12\n\nfile_paths\x18\x01 \x03(\t\"#\n\x10IndexingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"#\n\x0eSearchResponse\x12\x11\n\tdocuments\x18\x01 \x03(\t2x\n\x10SearchingService\x12\x34\n\x0bRunIndexing\x12\x10.IndexingRequest\x1a\x11.IndexingResponse\"\x00\x12.\n\tRunSearch\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'searching_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INDEXINGREQUEST']._serialized_start=27
  _globals['_INDEXINGREQUEST']._serialized_end=64
  _globals['_INDEXINGRESPONSE']._serialized_start=66
  _globals['_INDEXINGRESPONSE']._serialized_end=101
  _globals['_SEARCHREQUEST']._serialized_start=103
  _globals['_SEARCHREQUEST']._serialized_end=133
  _globals['_SEARCHRESPONSE']._serialized_start=135
  _globals['_SEARCHRESPONSE']._serialized_end=170
  _globals['_SEARCHINGSERVICE']._serialized_start=172
  _globals['_SEARCHINGSERVICE']._serialized_end=292
# @@protoc_insertion_point(module_scope)
